import type { RuntimeLanguage } from "@bloom/api-client";

/**
 * Status words the renderers write themselves, in the profile's language. The runtime chrome has its own
 * table; these were English on a French or Spanish screen. ES and FR still need a native speaker's check.
 */
const STRINGS = {
  en: {
    gauge: "Gauge",
    noSource: "no source",
    updatedAt: (time: string) => `updated ${time}`,
    sampleCount: (count: number) => (count === 1 ? "1 sample" : `${count} samples`),
    historyWindow: (seconds: number) => `${seconds}s history`,
    plotLabel: (title: string) => `${title} plot`,
    latestReading: "latest",
    frozenReading: "frozen",
    liveFrom: (topic: string) => `live from ${topic}`,
    newestFirst: "newest first",
    eventCount: (count: number) => (count === 1 ? "1 event" : `${count} events`),
    secondsAgo: (count: number) => `${count} s ago`,
    minutesAgo: (count: number) => `${count} min ago`,
    hoursAgo: (count: number) => `${count} h ago`,
    noEventsYet: "No events yet",
    noEventsDetail: "Connect a runtime log source or configure static events for this screen.",
    eventReceived: "Runtime event received",
    stale: "stale",
    view3d: (title: string) => `${title} 3D view`,
    desktopOnly: "Desktop screens only.",
    noRobotModel: "No robot model source in this runtime.",
    cannotDraw3d: "This browser cannot draw 3D.",
    noRobotDescription: "No robot description from the API yet. Launch the robot; the view keeps asking.",
    loading3d: "Loading the 3D view.",
    gestureHint: "Drag to turn · wheel to zoom",
    frameRobot: "Frame the robot",
    frame: "Frame",
    waitingJointStates: "Waiting for joint states",
    markersFrom: (topic: string) => `markers ${topic}`,
    jointStateReceived: "Live joint state received",
    liveJoints: (count: number) => (count === 1 ? "1 live joint" : `${count} live joints`),
    jointsDriven: (live: string, driven: number, total: number) => `${live}, ${driven} of the model's ${total} driven`,
    cameraNoTopic: "No topic",
    cameraTopicNeeded: "Topic needed",
    cameraLocal: "Local camera",
    cameraStreamConfigured: "Stream configured",
    cameraNoSource: "No source",
    cameraNotConfigured: "No camera source configured yet.",
    cameraReady: "Ready",
    cameraSourceNeeded: "Source needed",
    cameraPicker: "Camera",
    cameraAuto: "Auto",
    webcamStatus: {
      error: "Webcam unavailable",
      idle: "Preparing webcam",
      ready: "Webcam live",
      requesting: "Requesting webcam permission",
      unsupported: "Webcam unsupported",
    },
    cameraClosed: "The camera stream closed.",
    cameraConnecting: "Connecting…",
    cameraNameTopic: "Name a compressed image topic to show a camera.",
    cameraNoRos: "This backend has no ROS node, so no camera can reach it.",
    cameraReconnecting: "Reconnecting…",
    cameraStale: (seconds: number) => `No new frame for ${seconds} s`,
    cameraStalled: "The camera stopped sending.",
    cameraWaiting: (topic: string) => `Waiting for a frame on ${topic}.`,
    jointsStale: (seconds: number) => `No joint state for ${seconds} s. The robot is drawn where it last was.`,
    jointsStalled: "Joint states stopped arriving.",
    notSent: "Not sent.",
    stepHints: { dwell: "rest to move", scan: "scan", step: "step" },
    zero: (title: string) => `Zero ${title}`,
    stop: (title: string) => `Stop ${title}`,
    oneStep: (label: string) => `${label}, one step`,
    increase: (title: string, step: number) => `Increase ${title} by ${step}`,
    decrease: (title: string, step: number) => `Decrease ${title} by ${step}`,
    stepControls: (title: string) => `${title} step controls`,
    freeze: "Freeze",
    zeroButton: "Zero",
    live: "Live",
    releasesIn: (seconds: number) => `Releases in ${seconds} s`,
    keepGoing: "Keep going",
    releasesSoon: "This control lets go in a few seconds.",
    released: "Released after a while without input.",
    armedFor: (seconds: number) => `arms for ${seconds} s, then cancels itself`,
    armedUntilPressed: "stays armed until pressed again",
    requested: "requested",
    notRequested: "not requested",
    lastRequested: (detail: string) => `Last requested \u00b7 ${detail}`,
  },
  fr: {
    gauge: "Jauge",
    noSource: "aucune source",
    updatedAt: (time: string) => `mis à jour à ${time}`,
    sampleCount: (count: number) => (count === 1 ? "1 échantillon" : `${count} échantillons`),
    historyWindow: (seconds: number) => `historique de ${seconds} s`,
    plotLabel: (title: string) => `Courbe : ${title}`,
    latestReading: "dernière valeur",
    frozenReading: "valeur figée",
    liveFrom: (topic: string) => `en direct de ${topic}`,
    newestFirst: "plus récents en premier",
    eventCount: (count: number) => (count === 1 ? "1 événement" : `${count} événements`),
    secondsAgo: (count: number) => `il y a ${count} s`,
    minutesAgo: (count: number) => `il y a ${count} min`,
    hoursAgo: (count: number) => `il y a ${count} h`,
    noEventsYet: "Aucun événement pour l'instant",
    noEventsDetail: "Connectez une source de journal ou configurez des événements statiques pour cet écran.",
    eventReceived: "Événement reçu",
    stale: "plus à jour",
    view3d: (title: string) => `Vue 3D : ${title}`,
    desktopOnly: "Écrans d'ordinateur uniquement.",
    noRobotModel: "Aucune source de modèle du robot dans ce runtime.",
    cannotDraw3d: "Ce navigateur ne peut pas afficher la 3D.",
    noRobotDescription:
      "Pas encore de description du robot depuis l'API. Lancez le robot ; la vue continue de la demander.",
    loading3d: "Chargement de la vue 3D.",
    gestureHint: "Glisser pour tourner · molette pour zoomer",
    frameRobot: "Cadrer le robot",
    frame: "Cadrer",
    waitingJointStates: "En attente des états articulaires",
    markersFrom: (topic: string) => `marqueurs ${topic}`,
    jointStateReceived: "État articulaire reçu",
    liveJoints: (count: number) => (count === 1 ? "1 articulation en direct" : `${count} articulations en direct`),
    jointsDriven: (live: string, driven: number, total: number) =>
      `${live}, ${driven} sur les ${total} du modèle pilotées`,
    cameraNoTopic: "Aucun topic",
    cameraTopicNeeded: "Topic requis",
    cameraLocal: "Caméra locale",
    cameraStreamConfigured: "Flux configuré",
    cameraNoSource: "Aucune source",
    cameraNotConfigured: "Aucune source de caméra configurée.",
    cameraReady: "Prête",
    cameraSourceNeeded: "Source requise",
    cameraPicker: "Caméra",
    cameraAuto: "Auto",
    webcamStatus: {
      error: "Webcam indisponible",
      idle: "Préparation de la webcam",
      ready: "Webcam en direct",
      requesting: "Demande d'accès à la webcam",
      unsupported: "Webcam non prise en charge",
    },
    cameraClosed: "Le flux de la caméra s'est fermé.",
    cameraConnecting: "Connexion…",
    cameraNameTopic: "Indiquez un topic d'image compressée pour afficher une caméra.",
    cameraNoRos: "Ce serveur n'a pas de nœud ROS : aucune caméra ne peut l'atteindre.",
    cameraReconnecting: "Reconnexion…",
    cameraStale: (seconds: number) => `Aucune nouvelle image depuis ${seconds} s`,
    cameraStalled: "La caméra n'envoie plus d'images.",
    cameraWaiting: (topic: string) => `En attente d'une image sur ${topic}.`,
    jointsStale: (seconds: number) =>
      `Aucun état articulaire depuis ${seconds} s. Le robot est dessiné à sa dernière position.`,
    jointsStalled: "Les états articulaires n'arrivent plus.",
    notSent: "Non envoyé.",
    stepHints: { dwell: "reposer pour bouger", scan: "balayage", step: "pas à pas" },
    zero: (title: string) => `Remettre à zéro : ${title}`,
    stop: (title: string) => `Arrêter : ${title}`,
    oneStep: (label: string) => `${label}, un pas`,
    increase: (title: string, step: number) => `Augmenter ${title} de ${step}`,
    decrease: (title: string, step: number) => `Diminuer ${title} de ${step}`,
    stepControls: (title: string) => `Commandes pas à pas : ${title}`,
    freeze: "Figer",
    zeroButton: "Zéro",
    live: "En direct",
    releasesIn: (seconds: number) => `Relâché dans ${seconds} s`,
    keepGoing: "Continuer",
    releasesSoon: "Cette commande se relâche dans quelques secondes.",
    released: "Relâchée faute d'action.",
    armedFor: (seconds: number) => `armé pendant ${seconds} s, puis s'annule`,
    armedUntilPressed: "reste armé jusqu'au prochain appui",
    requested: "demandé",
    notRequested: "non demandé",
    lastRequested: (detail: string) => `Dernière demande \u00b7 ${detail}`,
  },
  es: {
    gauge: "Indicador",
    noSource: "sin fuente",
    updatedAt: (time: string) => `actualizado a las ${time}`,
    sampleCount: (count: number) => (count === 1 ? "1 muestra" : `${count} muestras`),
    historyWindow: (seconds: number) => `historial de ${seconds} s`,
    plotLabel: (title: string) => `Gráfica: ${title}`,
    latestReading: "último valor",
    frozenReading: "valor congelado",
    liveFrom: (topic: string) => `en vivo desde ${topic}`,
    newestFirst: "más recientes primero",
    eventCount: (count: number) => (count === 1 ? "1 evento" : `${count} eventos`),
    secondsAgo: (count: number) => `hace ${count} s`,
    minutesAgo: (count: number) => `hace ${count} min`,
    hoursAgo: (count: number) => `hace ${count} h`,
    noEventsYet: "Aún no hay eventos",
    noEventsDetail: "Conecte una fuente de registro o configure eventos estáticos para esta pantalla.",
    eventReceived: "Evento recibido",
    stale: "desactualizado",
    view3d: (title: string) => `Vista 3D: ${title}`,
    desktopOnly: "Solo en pantallas de ordenador.",
    noRobotModel: "Ninguna fuente de modelo del robot en este runtime.",
    cannotDraw3d: "Este navegador no puede mostrar 3D.",
    noRobotDescription: "Aún no hay descripción del robot desde la API. Lance el robot; la vista sigue pidiéndola.",
    loading3d: "Cargando la vista 3D.",
    gestureHint: "Arrastrar para girar · rueda para ampliar",
    frameRobot: "Encuadrar el robot",
    frame: "Encuadrar",
    waitingJointStates: "Esperando los estados articulares",
    markersFrom: (topic: string) => `marcadores ${topic}`,
    jointStateReceived: "Estado articular recibido",
    liveJoints: (count: number) => (count === 1 ? "1 articulación en vivo" : `${count} articulaciones en vivo`),
    jointsDriven: (live: string, driven: number, total: number) =>
      `${live}, ${driven} de las ${total} del modelo accionadas`,
    cameraNoTopic: "Sin topic",
    cameraTopicNeeded: "Topic requerido",
    cameraLocal: "Cámara local",
    cameraStreamConfigured: "Flujo configurado",
    cameraNoSource: "Sin fuente",
    cameraNotConfigured: "Ninguna fuente de cámara configurada.",
    cameraReady: "Lista",
    cameraSourceNeeded: "Fuente requerida",
    cameraPicker: "Cámara",
    cameraAuto: "Auto",
    webcamStatus: {
      error: "Webcam no disponible",
      idle: "Preparando la webcam",
      ready: "Webcam en vivo",
      requesting: "Solicitando acceso a la webcam",
      unsupported: "Webcam no compatible",
    },
    cameraClosed: "El flujo de la cámara se cerró.",
    cameraConnecting: "Conectando…",
    cameraNameTopic: "Indique un topic de imagen comprimida para mostrar una cámara.",
    cameraNoRos: "Este servidor no tiene nodo ROS: ninguna cámara puede llegar.",
    cameraReconnecting: "Reconectando…",
    cameraStale: (seconds: number) => `Ninguna imagen nueva desde hace ${seconds} s`,
    cameraStalled: "La cámara dejó de enviar imágenes.",
    cameraWaiting: (topic: string) => `Esperando una imagen en ${topic}.`,
    jointsStale: (seconds: number) =>
      `Ningún estado articular desde hace ${seconds} s. El robot se dibuja donde estaba.`,
    jointsStalled: "Los estados articulares dejaron de llegar.",
    notSent: "No enviado.",
    stepHints: { dwell: "reposar para mover", scan: "barrido", step: "paso a paso" },
    zero: (title: string) => `Poner a cero: ${title}`,
    stop: (title: string) => `Detener: ${title}`,
    oneStep: (label: string) => `${label}, un paso`,
    increase: (title: string, step: number) => `Aumentar ${title} en ${step}`,
    decrease: (title: string, step: number) => `Disminuir ${title} en ${step}`,
    stepControls: (title: string) => `Controles paso a paso: ${title}`,
    freeze: "Congelar",
    zeroButton: "Cero",
    live: "En vivo",
    releasesIn: (seconds: number) => `Se suelta en ${seconds} s`,
    keepGoing: "Continuar",
    releasesSoon: "Este control se suelta en unos segundos.",
    released: "Soltado por falta de acción.",
    armedFor: (seconds: number) => `armado durante ${seconds} s, luego se cancela`,
    armedUntilPressed: "sigue armado hasta la próxima pulsación",
    requested: "solicitado",
    notRequested: "no solicitado",
    lastRequested: (detail: string) => `Última solicitud \u00b7 ${detail}`,
  },
} as const;

export function rendererStrings(language: RuntimeLanguage | undefined) {
  return STRINGS[language === "fr" || language === "es" ? language : "en"];
}

export type RendererStrings = ReturnType<typeof rendererStrings>;
