import type { RuntimeStrings } from "./types";

export const enRuntimeStrings: RuntimeStrings = {
  language: "en",
  status: { connecting: "CONNECTING", linkDown: "LINK DOWN", ready: "READY", stopped: "STOPPED" },
  stop: {
    engage: "STOP",
    engageAria: "Stop the robot",
    resume: "HOLD TO RESUME",
    resumeAria: "Hold for one second to resume",
  },
  scan: {
    button: "SWITCH - press Space or tap here",
    progress: (current, total) => `Scanning ${current} of ${total}.`,
  },
  tour: {
    close: "Close practice",
    complete: "Complete",
    disconnected: "Practice controls disconnected from robot commands",
    localOnly: "Local practice - nothing here can command the robot",
    movementFallback: "movement control",
    moveBody: (controlName, directionLabel, count) =>
      `Use ${directionLabel} on ${controlName} twice. Practice movement ${Math.min(count, 2)} of 2.`,
    practice: "Guided practice",
    progress: (complete, total) => `${complete} of ${total} practice steps complete`,
    screenBody: (applicationName, screenTitle) =>
      `${applicationName} is open on ${screenTitle}. The top strip reports the session; the fixed red control stops it.`,
    steps: {
      screen: {
        title: "This is your screen",
        body: "The top strip reports the session and the fixed red control stops it.",
        why: "Operation keeps exits and editing tools away from the controls under your hand.",
        action: "I've seen it",
      },
      move: {
        title: "Move the arm",
        body: "Use the named movement control twice.",
        why: "This practice control uses the app's own label but has no robot command connection.",
        action: "Move forward",
      },
      stop: {
        title: "Stop, and start again",
        body: "Stop the practice session, then hold to resume it.",
        why: "Stopping is immediate. Resuming takes a deliberate hold so a second stray tap cannot restart movement.",
        action: "Stop practice",
      },
      settings: {
        title: "Make it fit your hand",
        body: "Hold the maintenance control to find your movement, timing, direction, language, and display settings.",
        why: "The settings use your current scanning and dwell behavior and never send preview movement to the robot.",
        action: "Hold maintenance",
      },
      ready: {
        title: "You're ready",
        body: "Leave local practice and return to the live operator screen.",
        why: "Only leaving this disconnected practice surface restores the application's real command controls.",
        action: "Start for real",
      },
    },
    stepsLabel: "Practice steps",
    title: "Practice this app",
    whyTitle: "Why this matters",
  },
  workspace: {
    application: "Runtime application",
    comingSoon: "Coming soon",
    comingSoonDescription: "This screen exists in the application model, but it does not have runtime content yet.",
    comingSoonRegion: "Runtime screen coming soon",
  },
  kiosk: {
    appLibrary: "App library",
    backToOperation: "Back to operation",
    editApp: "Edit app",
    editScreen: "Edit this screen in the builder",
    fitDescription: (width, height, percent) =>
      `Composed for ${width} × ${height}, shown at ${percent}%. Targets may be below the 44 px touch floor.`,
    fitTitle: "Touch targets scaled down",
    gamepad: "gamepad",
    help: "Help",
    home: "Home",
    maintenance: "Maintenance",
    maintenanceAria: "Hold to open maintenance",
    maintenanceHelp: "Held for 1.5s. The robot keeps its last commanded state while this is open.",
    referenceFrameTitle: "Reference frame for operator commands",
    robotTitle: "Robot this backend drives",
    settings: "Settings",
    supervisorMirror: "Supervisor mirror",
    switchScreen: "Switch runtime screen",
  },
  supervisor: {
    application: "Application",
    backToLibrary: "Back to app library",
    commandFrame: "Configured frame",
    lastRequest: "Last requested mode",
    neverRequested: "No mode request observed in this browser session",
    notReported: "Not reported",
    operatorOwnsControl: "Operator retains control",
    ownershipDetail: "This mirror can observe status. It has no movement, STOP, resume, publish, or action controls.",
    readOnly: "Read-only live status",
    robot: "Robot",
    running: "Running",
    status: {
      api: "API",
      checking: "Checking",
      connected: "Connected",
      live: "Live",
      local: "Local",
      missing: "Missing",
      mode: "Mode",
      noPublisher: "No publisher",
      noSubscriber: "No subscriber",
      notChecked: "Not checked",
      panelLabel: "Runtime robot status",
      refresh: "Refresh status",
      refreshFailed: "Runtime status refresh failed.",
      session: "Session",
      topicsLoaded: (count) => `${count} topic diagnostics loaded.`,
      topicListLabel: "Runtime topic status",
      unavailable: "Unavailable",
    },
    stopLatch: "Stop latch",
    stopped: "Stopped",
    title: "Supervisor mirror",
    updatedAt: (value) => `Requested ${value}`,
  },
  settings: {
    title: "Settings",
    profileName: (name) => `${name}'s profile`,
    practiceTour: "Practice tour",
    undo: "Undo changes",
    done: "Done",
    categories: {
      movement: "How I move it",
      tuning: "Fine tuning",
      frame: "Which way is forward",
      language: "Language",
      display: "Reading the screen",
    },
    movementEyebrow: "Movement",
    movementHeading: "How should the controls respond?",
    movementFallback: "Choose how controls respond to your movement.",
    movementChoices: {
      default: { label: "Drag", description: "Move while your hand stays on the control." },
      step: { label: "Tap by tap", description: "Each tap moves one small step." },
      latch: { label: "Keep going", description: "Movement continues after you let go; tap again to stop." },
      edge: { label: "At the edge", description: "Edge movement is not available in this runtime yet." },
      scan: { label: "One switch", description: "A highlight moves through every available control." },
    },
    tuningEyebrow: "Fine tuning",
    tuningHeading: "Adjust one clear step at a time.",
    scanSpeed: "Scan speed",
    smallMovements: "Ignore small movements",
    dwellLabel: "Hold before it counts",
    dwellHelp: "Rest on a control to select it",
    restToSelect: "Rest to select",
    repeatGuard: "Ignore repeated taps",
    statusSounds: "Status sounds",
    statusSoundsHelp: "Hear stop, link loss, and recovery",
    valueOn: "On",
    valueOff: "Off",
    decrease: (label) => `Decrease ${label}`,
    increase: (label) => `Increase ${label}`,
    value: (label) => `${label} value`,
    directionEyebrow: "Direction",
    directionHeading: "Choose what forward follows.",
    directionRelease: "Release every movement control before changing direction.",
    frameUnavailable: "The connected runtime has not reported any command frames.",
    frameFallback: "Use this frame reported by the connected runtime.",
    frameDescriptions: {
      base_link: { label: "Robot axes", description: "Forward stays aligned with the robot base." },
      effector_frame: { label: "Tool direction", description: "Forward follows the tool at the end of the arm." },
      hybrid_frame: { label: "Where I look", description: "Translation follows the operator-facing hybrid frame." },
      ft_frame: { label: "Force sensor", description: "Forward follows the force sensor frame." },
    },
    languageEyebrow: "Language",
    languageHeading: "Choose your language.",
    displayEyebrow: "Reading the screen",
    displayHeading: "Installed display profile",
    displayLabel: "Display",
    textSize: "Text size",
    displayFixed: "Display settings are fixed during tablet installation.",
    displayPresets: {
      compact: "Compact",
      comfort: "Comfort",
      default: "Default",
      "high-visibility": "High visibility",
    },
    safePreview: "Safe preview",
    tryTitle: "Try it here",
    tryHelp: "These buttons never send anything to the robot.",
    tryLeft: "Left",
    tryForward: "Forward",
    tryRight: "Right",
  },
};
