import type { RuntimeStrings } from "./types";

export const enRuntimeStrings: RuntimeStrings = {
  language: "en",
  status: { connecting: "CONNECTING", linkDown: "LINK DOWN", ready: "READY", stopped: "STOPPED" },
  stop: {
    engage: "STOP",
    engageAria: "Stop the robot",
    resume: "HOLD TO RESUME",
    resumeAria: "Hold for one second to resume",
  },
  scan: {
    button: "SWITCH - press Space or tap here",
    progress: (current, total) => `Scanning ${current} of ${total}.`,
  },
  workspace: {
    application: "Runtime application",
    comingSoon: "Coming soon",
    comingSoonDescription: "This screen exists in the application model, but it does not have runtime content yet.",
    comingSoonRegion: "Runtime screen coming soon",
  },
  kiosk: {
    appLibrary: "App library",
    backToOperation: "Back to operation",
    editApp: "Edit app",
    editScreen: "Edit this screen in the builder",
    fitDescription: (width, height, percent) =>
      `Composed for ${width} × ${height}, shown at ${percent}%. Targets may be below the 44 px touch floor.`,
    fitTitle: "Touch targets scaled down",
    gamepad: "gamepad",
    help: "Help",
    home: "Home",
    maintenance: "Maintenance",
    maintenanceAria: "Hold to open maintenance",
    maintenanceHelp: "Held for 1.5s. The robot keeps its last commanded state while this is open.",
    referenceFrameTitle: "Reference frame for operator commands",
    robotTitle: "Robot this backend drives",
    settings: "Settings",
    switchScreen: "Switch runtime screen",
  },
  settings: {
    title: "Settings",
    profileName: (name) => `${name}'s profile`,
    undo: "Undo changes",
    done: "Done",
    categories: {
      movement: "How I move it",
      tuning: "Fine tuning",
      frame: "Which way is forward",
      language: "Language",
      display: "Reading the screen",
    },
    movementEyebrow: "Movement",
    movementHeading: "How should the controls respond?",
    movementFallback: "Choose how controls respond to your movement.",
    movementChoices: {
      default: { label: "Drag", description: "Move while your hand stays on the control." },
      step: { label: "Tap by tap", description: "Each tap moves one small step." },
      latch: { label: "Keep going", description: "Movement continues after you let go; tap again to stop." },
      edge: { label: "At the edge", description: "Edge movement is not available in this runtime yet." },
      scan: { label: "One switch", description: "A highlight moves through every available control." },
    },
    tuningEyebrow: "Fine tuning",
    tuningHeading: "Adjust one clear step at a time.",
    scanSpeed: "Scan speed",
    smallMovements: "Ignore small movements",
    dwellLabel: "Hold before it counts",
    dwellHelp: "Rest on a control to select it",
    restToSelect: "Rest to select",
    repeatGuard: "Ignore repeated taps",
    statusSounds: "Status sounds",
    statusSoundsHelp: "Hear stop, link loss, and recovery",
    valueOn: "On",
    valueOff: "Off",
    decrease: (label) => `Decrease ${label}`,
    increase: (label) => `Increase ${label}`,
    value: (label) => `${label} value`,
    directionEyebrow: "Direction",
    directionHeading: "Choose what forward follows.",
    directionRelease: "Release every movement control before changing direction.",
    frameUnavailable: "The connected runtime has not reported any command frames.",
    frameFallback: "Use this frame reported by the connected runtime.",
    frameDescriptions: {
      base_link: { label: "Robot axes", description: "Forward stays aligned with the robot base." },
      effector_frame: { label: "Tool direction", description: "Forward follows the tool at the end of the arm." },
      hybrid_frame: { label: "Where I look", description: "Translation follows the operator-facing hybrid frame." },
      ft_frame: { label: "Force sensor", description: "Forward follows the force sensor frame." },
    },
    languageEyebrow: "Language",
    languageHeading: "Choose your language.",
    displayEyebrow: "Reading the screen",
    displayHeading: "Installed display profile",
    displayLabel: "Display",
    textSize: "Text size",
    displayFixed: "Display settings are fixed during tablet installation.",
    displayPresets: {
      compact: "Compact",
      comfort: "Comfort",
      default: "Default",
      "high-visibility": "High visibility",
    },
    safePreview: "Safe preview",
    tryTitle: "Try it here",
    tryHelp: "These buttons never send anything to the robot.",
    tryLeft: "Left",
    tryForward: "Forward",
    tryRight: "Right",
  },
};
