import type { RuntimeStrings } from "./types";

export const enRuntimeStrings: RuntimeStrings = {
  language: "en",
  status: {
    connecting: "CONNECTING",
    debug: "DEBUG",
    held: "HELD FOR MAINTENANCE",
    linkDown: "LINK DOWN",
    notInControl: "NOT IN CONTROL",
    ready: "READY",
    stopped: "STOPPED",
  },
  stop: {
    engage: "STOP",
    engageAria: "Stop the robot",
    resume: "HOLD TO RESUME",
    resumeAria: "Hold for one second to resume",
    resumeConfirm: "PRESS AGAIN TO RESUME",
    resumeConfirmAria: "Press again to resume",
  },
  control: {
    anotherOwner: "Another operator controls this robot",
    claim: "Take control",
    claiming: "Claiming control...",
    noOwner: "No operator currently controls this robot",
    resumeRequiresOwner: "Take control before resuming the robot.",
  },
  scan: {
    button: "SWITCH - press Space or tap here",
    progress: (current, total) => `Scanning ${current} of ${total}.`,
  },
  tour: {
    close: "Close practice",
    complete: "Complete",
    disconnected: "Practice controls disconnected from robot commands",
    localOnly: "Local practice - nothing here can command the robot",
    movementFallback: "movement control",
    offerAria: "First time here?",
    offerDismiss: "Not now",
    offerStart: "Practice first",
    moveBody: (controlName, directionLabel, count) =>
      `Use ${directionLabel} on ${controlName} twice. Practice movement ${Math.min(count, 2)} of 2.`,
    practice: "Guided practice",
    progress: (complete, total) => `${complete} of ${total} practice steps complete`,
    screenBody: (applicationName, screenTitle) =>
      `${applicationName} is open on ${screenTitle}. The top strip reports the session; the fixed red control stops it.`,
    steps: {
      screen: {
        title: "This is your screen",
        body: "The top strip reports the session and the fixed red control stops it.",
        why: "Operation keeps exits and editing tools away from the controls under your hand.",
        action: "I've seen it",
      },
      move: {
        title: "Move the arm",
        body: "Use the named movement control twice.",
        why: "This practice control uses the app's own label but has no robot command connection.",
        action: "Move forward",
      },
      stop: {
        title: "Stop, and start again",
        body: "Stop the practice session, then hold to resume it.",
        why: "Stopping is immediate. Resuming takes a deliberate hold so a second stray tap cannot restart movement.",
        action: "Stop practice",
      },
      settings: {
        title: "Make it fit your hand",
        body: "Hold the maintenance control to find your movement, timing, direction, language, and display settings.",
        why: "The settings use your current scanning and dwell behavior and never send preview movement to the robot.",
        action: "Hold maintenance",
      },
      ready: {
        title: "You're ready",
        body: "Leave local practice and return to the live operator screen.",
        why: "Only leaving this disconnected practice surface restores the application's real command controls.",
        action: "Start for real",
      },
    },
    stepsLabel: "Practice steps",
    title: "Practice this app",
    whyTitle: "Why this matters",
  },
  workspace: {
    application: "Runtime application",
    comingSoon: "Coming soon",
    comingSoonDescription: "This screen exists in the application model, but it does not have runtime content yet.",
    comingSoonRegion: "Runtime screen coming soon",
  },
  kiosk: {
    appLibrary: "App library",
    backToOperation: "Back to operation",
    commandFailed: "Command failed",
    commandNotSent: "Not sent",
    editApp: "Edit app",
    editScreen: "Edit this screen in the builder",
    fitDescription: (width, height, percent) =>
      `Composed for ${width} × ${height}, shown at ${percent}%. Targets may be below the 44 px touch floor.`,
    fitTitle: "Touch targets scaled down",
    frameNotOnRobot: (frameId) =>
      `Command frame "${frameId}" is not available on this robot. Select an available frame before moving.`,
    frameReleaseControls: "Release controls.",
    frameUnavailableOnRobot: "Unavailable on this robot.",
    gamepad: "gamepad",
    help: "Help",
    home: "Home",
    maintenance: "Maintenance",
    maintenanceAria: "Hold to open maintenance",
    maintenanceHelp: "Motion is stopped while maintenance is open. Return controls to neutral before resuming.",
    referenceFrameTitle: "Reference frame for operator commands",
    settings: "Settings",
    supervisorMirror: "Supervisor mirror",
    switchScreen: "Switch runtime screen",
    rate: (hz) => `${hz} Hz`,
    ratePublishing: (hz) => `publishing · ${hz} Hz`,
    rateZerosHeld: "zeros held",
    heldBadge: "Robot held at zeros",
    stoppedBadge: "Robot stopped",
    close: "Close",
    facts: {
      app: "App",
      commandFrame: "Command frame",
      commandFrameNote: "stamped on every twist",
      deviceClass: "Device class",
      deviceDesktop: "Desktop",
      deviceNote: (width, height) => `${width}×${height} · authored`,
      deviceTablet: "Tablet",
      gamepadConnected: (name) => `gamepad: ${name}`,
      link: "Link",
      linkNote: "frontend to backend, not the arm",
      notReported: "Not reported",
      profile: "Profile",
      publishRate: "Publish rate",
      publishRateNote: "while moving; a release sends zeros",
      youControl: "you control the robot",
    },
    actions: "Actions",
    settingsHint: "text size, language, how you reach controls",
    switchRole: "Switch role",
    switchRoleAria: "Hold to switch role",
    switchRoleHint: "needs its own 1.5 s hold",
    switchRoleChoose: "Choose a role",
    reload: "Reload this app",
    reloadHint: "reloads Bloom; keeps your profile",
    exitToLibrary: "Exit to library",
    exitHint: "ends the session",
    more: "More",
    resumeNote:
      "Closing resumes publishing immediately. Nothing here changes what the app sends — topics, frame and rate are shown so you can read them, not set them.",
    resume: "Resume operating",
  },
  supervisor: {
    application: "Application",
    backToLibrary: "Back to app library",
    activeFrame: "Active frame",
    commandFrame: "Configured frame",
    controlOwnerUnknown: "Control owner not reported",
    driving: "Driving",
    holding: "Holding still",
    lastRequest: "Last requested mode",
    neverRequested: "No mode request observed in this browser session",
    noOperatorOwnsControl: "No operator currently has control",
    noModeRequested: "No mode request reported by the operating session",
    notReported: "Not reported",
    operatorOwnsControl: "Operator retains control",
    ownershipDetail: "This mirror can observe status. It has no movement, STOP, resume, publish, or action controls.",
    readOnly: "Read-only live status",
    robot: "Robot",
    running: "Running",
    status: {
      api: "API",
      checking: "Checking",
      connected: "Connected",
      live: "Live",
      local: "Local",
      missing: "Missing",
      mode: "Mode",
      noPublisher: "No publisher",
      noSubscriber: "No subscriber",
      notChecked: "Not checked",
      panelLabel: "Runtime robot status",
      refresh: "Refresh status",
      refreshFailed: "Runtime status refresh failed.",
      session: "Session",
      topicsLoaded: (count) => `${count} topic diagnostics loaded.`,
      topicListLabel: "Runtime topic status",
      unavailable: "Unavailable",
    },
    stopLatch: "Stop latch",
    stopped: "Stopped",
    title: "Supervisor mirror",
    updatedAt: (value) => `Requested ${value}`,
  },
  library: {
    brand: "Bloom",
    title: "Runtime library",
    appsLabel: "Apps on this robot",
    openAsLabel: "Open as",
    openAs: (role) => `Open as ${role}`,
    open: "Open",
    screens: (count) => (count === 1 ? "1 screen" : `${count} screens`),
    classes: {
      tablet: "Tablet",
      desktop: "Desktop",
      both: "tablet + desktop",
      tabletOnly: "tablet only",
      desktopOnly: "desktop only",
    },
    archived: "Archived",
    active: "active",
    roleNote: "Opens as the role used last on this device. Pick another to open as that one.",
    lastUsed: "last used",
    noProfiles: "This app declares no profiles, so it opens with runtime defaults.",
    tagline: {
      accessible: "accessible",
      debugging: "debugging",
      scan: "scan",
      dwell: "dwell",
      plainLanguage: "plain language",
      continuousLimits: "continuous limits",
      period: (seconds) => `${seconds} s period`,
      target: (px) => `${px} px`,
    },
    supervisorAria: (appName) => `Open ${appName} supervisor mirror`,
    thisDevice: "This device",
    deviceTablet: (width, height) => `Tablet · ${width}×${height} · touch · 48 px floor, 64 px on accessible profiles`,
    deviceDesktop: (width, height) =>
      `Desktop · ${width}×${height} · mouse and keyboard · 40 px floor unless the profile raises it`,
    empty: "No apps are installed on this robot yet.",
    menu: "Library menu",
    builder: "Builder",
  },
  settings: {
    title: "Settings",
    practiceTour: "Practice tour",
    display: "Display",
    textSize: "Text size",
    textSizes: { normal: "Normal", large: "Large", larger: "Larger" },
    language: "Language",
    sound: "Sound on every press",
    valueOn: "On",
    valueOff: "Off",
    reach: "How you reach the controls",
    inputMethod: "Input method",
    inputMethods: { touch: "Touch", dwell: "Dwell", scan: "Scan" },
    pushMoves: "How a push moves",
    pushModes: { drag: "Drag", step: "Tap by tap", latch: "Keep going" },
    onlyFor: (method) => `only for ${method}`,
    onlyForTouchAndDwell: "only for Touch and Dwell",
    timing: "Timing",
    timingTouch: "Timing — touch needs no timing",
    holdToActivate: "Hold to activate",
    scanStep: "Scan step",
    ignoreRepeats: "Ignore repeats within",
    deadzone: "Joystick dead zone",
    deadzoneWidgetDefault: "each control's own",
    decrease: (label) => `Decrease ${label}`,
    increase: (label) => `Increase ${label}`,
    value: (label) => `${label} value`,
    tryIt: "Try it — nothing is sent",
    tryTitle: "Try a press",
    tryIdle: "Press to try. Nothing is sent.",
    tryPressed: (count) => `Pressed ${count} ${count === 1 ? "time" : "times"}. Nothing was sent.`,
    tryReadout: (targetPx, fontScale, timing) => `target ${targetPx} px · font ${fontScale} · ${timing}`,
    immediate: "immediate",
    tryForward: "Forward",
    saveAndResume: "Save and resume",
    discardChanges: "Discard changes",
    savedTo: "Saved to",
    savedToBody: (profileName) =>
      `The ${profileName} profile on this device. It does not change what the app publishes, only how you reach it.`,
  },
};
