import type { RuntimeStrings } from "./types";

export const esRuntimeStrings: RuntimeStrings = {
  language: "es",
  status: { connecting: "CONECTANDO", linkDown: "SIN CONEXIÓN", ready: "LISTO", stopped: "DETENIDO" },
  stop: {
    engage: "PARAR",
    engageAria: "Detener el robot",
    resume: "MANTENER PARA REANUDAR",
    resumeAria: "Mantener un segundo para reanudar",
  },
  scan: {
    button: "PULSADOR - pulsa Espacio o toca aquí",
    progress: (current, total) => `Barrido ${current} de ${total}.`,
  },
  tour: {
    close: "Cerrar práctica",
    complete: "Completado",
    disconnected: "Controles de práctica desconectados de los comandos del robot",
    localOnly: "Práctica local - nada aquí puede controlar el robot",
    movementFallback: "control de movimiento",
    moveBody: (controlName, directionLabel, count) =>
      `Usa ${directionLabel} en ${controlName} dos veces. Movimiento ${Math.min(count, 2)} de 2.`,
    practice: "Práctica guiada",
    progress: (complete, total) => `${complete} de ${total} pasos completados`,
    screenBody: (applicationName, screenTitle) =>
      `${applicationName} está abierta en ${screenTitle}. La barra superior muestra la sesión; el control rojo fijo la detiene.`,
    steps: {
      screen: {
        title: "Esta es tu pantalla",
        body: "La barra superior muestra la sesión y el control rojo fijo la detiene.",
        why: "La operación mantiene las salidas y la edición lejos de los controles bajo tu mano.",
        action: "Ya la he visto",
      },
      move: {
        title: "Mover el brazo",
        body: "Usa dos veces el control de movimiento indicado.",
        why: "Este control usa el nombre de la app, pero no tiene conexión con los comandos del robot.",
        action: "Avanzar",
      },
      stop: {
        title: "Parar y volver a empezar",
        body: "Detén la práctica y mantén pulsado para reanudarla.",
        why: "La parada es inmediata. Reanudar exige mantener para evitar que otro toque reinicie el movimiento.",
        action: "Parar práctica",
      },
      settings: {
        title: "Adaptarla a tu mano",
        body: "Mantén mantenimiento para encontrar los ajustes de movimiento, tiempo, dirección, idioma y pantalla.",
        why: "Los ajustes usan tu barrido y reposo actuales y la prueba nunca envía movimiento al robot.",
        action: "Mantener mantenimiento",
      },
      ready: {
        title: "Todo listo",
        body: "Sal de la práctica local y vuelve a la pantalla de operación real.",
        why: "Los controles reales solo vuelven al salir de esta práctica desconectada.",
        action: "Empezar de verdad",
      },
    },
    stepsLabel: "Pasos de práctica",
    title: "Practicar esta app",
    whyTitle: "Por qué importa",
  },
  workspace: {
    application: "Aplicación de operación",
    comingSoon: "Próximamente",
    comingSoonDescription: "Esta pantalla existe en la aplicación, pero aún no tiene contenido operativo.",
    comingSoonRegion: "Pantalla de operación próximamente",
  },
  kiosk: {
    appLibrary: "Biblioteca de apps",
    backToOperation: "Volver al control",
    editApp: "Editar app",
    editScreen: "Editar esta pantalla",
    fitDescription: (width, height, percent) =>
      `Diseñada para ${width} x ${height}, mostrada al ${percent} %. Los objetivos pueden medir menos de 44 px.`,
    fitTitle: "Objetivos táctiles reducidos",
    gamepad: "mando",
    help: "Ayuda",
    home: "Inicio",
    maintenance: "Mantenimiento",
    maintenanceAria: "Mantener para abrir mantenimiento",
    maintenanceHelp: "Pulsado 1,5 s. El robot conserva el último estado ordenado mientras está abierto.",
    referenceFrameTitle: "Marco de referencia de los comandos",
    robotTitle: "Robot controlado por este servidor",
    settings: "Ajustes",
    supervisorMirror: "Vista de supervisión",
    switchScreen: "Cambiar pantalla de operación",
  },
  supervisor: {
    application: "Aplicación",
    backToLibrary: "Volver a la biblioteca de apps",
    commandFrame: "Marco configurado",
    lastRequest: "Último modo solicitado",
    neverRequested: "No se ha observado ninguna solicitud de modo en esta sesión del navegador",
    notReported: "No indicado",
    operatorOwnsControl: "El operador conserva el control",
    ownershipDetail:
      "Esta vista solo observa el estado. No tiene controles de movimiento, parada, reanudación, publicación ni acciones.",
    readOnly: "Estado en directo de solo lectura",
    robot: "Robot",
    running: "En marcha",
    status: {
      api: "API",
      checking: "Comprobando",
      connected: "Conectada",
      live: "Activa",
      local: "Local",
      missing: "Ausente",
      mode: "Modo",
      noPublisher: "Sin publicador",
      noSubscriber: "Sin suscriptor",
      notChecked: "No comprobado",
      panelLabel: "Estado del robot en operación",
      refresh: "Actualizar estado",
      refreshFailed: "No se pudo actualizar el estado de operación.",
      session: "Sesión",
      topicsLoaded: (count) => `${count} diagnósticos de topics cargados.`,
      topicListLabel: "Estado de los topics de operación",
      unavailable: "No disponible",
    },
    stopLatch: "Bloqueo de parada",
    stopped: "Detenido",
    title: "Vista de supervisión",
    updatedAt: (value) => `Solicitado ${value}`,
  },
  settings: {
    title: "Ajustes",
    profileName: (name) => `Perfil de ${name}`,
    practiceTour: "Práctica guiada",
    undo: "Deshacer cambios",
    done: "Terminar",
    categories: {
      movement: "Cómo lo muevo",
      tuning: "Ajuste fino",
      frame: "Dónde está delante",
      language: "Idioma",
      display: "Leer la pantalla",
    },
    movementEyebrow: "Movimiento",
    movementHeading: "¿Cómo deben responder los controles?",
    movementFallback: "Elige cómo responden los controles a tu movimiento.",
    movementChoices: {
      default: { label: "Arrastrar", description: "Se mueve mientras mantienes la mano en el control." },
      step: { label: "Poco a poco", description: "Cada toque mueve un paso pequeño." },
      latch: { label: "Seguir", description: "Continúa al soltar; toca otra vez para parar." },
      edge: { label: "En el borde", description: "El movimiento por borde aún no está disponible." },
      scan: { label: "Un pulsador", description: "Un resaltado recorre cada control disponible." },
    },
    tuningEyebrow: "Ajuste fino",
    tuningHeading: "Ajusta un paso claro cada vez.",
    scanSpeed: "Velocidad de barrido",
    smallMovements: "Ignorar movimientos pequeños",
    dwellLabel: "Espera antes de activar",
    dwellHelp: "Descansa sobre un control para elegirlo",
    restToSelect: "Reposo para elegir",
    repeatGuard: "Ignorar toques repetidos",
    statusSounds: "Sonidos de estado",
    statusSoundsHelp: "Oír parada, pérdida y recuperación",
    valueOn: "Sí",
    valueOff: "No",
    decrease: (label) => `Reducir ${label}`,
    increase: (label) => `Aumentar ${label}`,
    value: (label) => `Valor de ${label}`,
    directionEyebrow: "Dirección",
    directionHeading: "Elige qué define delante.",
    directionRelease: "Suelta todos los controles antes de cambiar la dirección.",
    frameUnavailable: "El sistema conectado no ha indicado marcos de comando.",
    frameFallback: "Usar este marco indicado por el sistema conectado.",
    frameDescriptions: {
      base_link: { label: "Ejes del robot", description: "Delante queda alineado con la base del robot." },
      effector_frame: {
        label: "Dirección de la herramienta",
        description: "Delante sigue la herramienta del extremo.",
      },
      hybrid_frame: { label: "Donde miro", description: "La traslación sigue el marco orientado al operador." },
      ft_frame: { label: "Sensor de fuerza", description: "Delante sigue el marco del sensor de fuerza." },
    },
    languageEyebrow: "Idioma",
    languageHeading: "Elige tu idioma.",
    displayEyebrow: "Leer la pantalla",
    displayHeading: "Perfil de pantalla instalado",
    displayLabel: "Pantalla",
    textSize: "Tamaño del texto",
    displayFixed: "La pantalla se configura durante la instalación de la tableta.",
    displayPresets: {
      compact: "Compacta",
      comfort: "Cómoda",
      default: "Predeterminada",
      "high-visibility": "Alta visibilidad",
    },
    safePreview: "Prueba segura",
    tryTitle: "Pruébalo aquí",
    tryHelp: "Estos botones nunca envían nada al robot.",
    tryLeft: "Izquierda",
    tryForward: "Adelante",
    tryRight: "Derecha",
  },
};
