import type { RuntimeStrings } from "./types";

export const esRuntimeStrings: RuntimeStrings = {
  language: "es",
  status: { connecting: "CONECTANDO", linkDown: "SIN CONEXIÓN", ready: "LISTO", stopped: "DETENIDO" },
  stop: {
    engage: "PARAR",
    engageAria: "Detener el robot",
    resume: "MANTENER PARA REANUDAR",
    resumeAria: "Mantener un segundo para reanudar",
  },
  scan: {
    button: "PULSADOR - pulsa Espacio o toca aquí",
    progress: (current, total) => `Barrido ${current} de ${total}.`,
  },
  workspace: {
    application: "Aplicación de operación",
    comingSoon: "Próximamente",
    comingSoonDescription: "Esta pantalla existe en la aplicación, pero aún no tiene contenido operativo.",
    comingSoonRegion: "Pantalla de operación próximamente",
  },
  kiosk: {
    appLibrary: "Biblioteca de apps",
    backToOperation: "Volver al control",
    editApp: "Editar app",
    editScreen: "Editar esta pantalla",
    fitDescription: (width, height, percent) =>
      `Diseñada para ${width} x ${height}, mostrada al ${percent} %. Los objetivos pueden medir menos de 44 px.`,
    fitTitle: "Objetivos táctiles reducidos",
    gamepad: "mando",
    help: "Ayuda",
    home: "Inicio",
    maintenance: "Mantenimiento",
    maintenanceAria: "Mantener para abrir mantenimiento",
    maintenanceHelp: "Pulsado 1,5 s. El robot conserva el último estado ordenado mientras está abierto.",
    referenceFrameTitle: "Marco de referencia de los comandos",
    robotTitle: "Robot controlado por este servidor",
    settings: "Ajustes",
    switchScreen: "Cambiar pantalla de operación",
  },
  settings: {
    title: "Ajustes",
    profileName: (name) => `Perfil de ${name}`,
    undo: "Deshacer cambios",
    done: "Terminar",
    categories: {
      movement: "Cómo lo muevo",
      tuning: "Ajuste fino",
      frame: "Dónde está delante",
      language: "Idioma",
      display: "Leer la pantalla",
    },
    movementEyebrow: "Movimiento",
    movementHeading: "¿Cómo deben responder los controles?",
    movementFallback: "Elige cómo responden los controles a tu movimiento.",
    movementChoices: {
      default: { label: "Arrastrar", description: "Se mueve mientras mantienes la mano en el control." },
      step: { label: "Poco a poco", description: "Cada toque mueve un paso pequeño." },
      latch: { label: "Seguir", description: "Continúa al soltar; toca otra vez para parar." },
      edge: { label: "En el borde", description: "El movimiento por borde aún no está disponible." },
      scan: { label: "Un pulsador", description: "Un resaltado recorre cada control disponible." },
    },
    tuningEyebrow: "Ajuste fino",
    tuningHeading: "Ajusta un paso claro cada vez.",
    scanSpeed: "Velocidad de barrido",
    smallMovements: "Ignorar movimientos pequeños",
    dwellLabel: "Espera antes de activar",
    dwellHelp: "Descansa sobre un control para elegirlo",
    restToSelect: "Reposo para elegir",
    repeatGuard: "Ignorar toques repetidos",
    statusSounds: "Sonidos de estado",
    statusSoundsHelp: "Oír parada, pérdida y recuperación",
    valueOn: "Sí",
    valueOff: "No",
    decrease: (label) => `Reducir ${label}`,
    increase: (label) => `Aumentar ${label}`,
    value: (label) => `Valor de ${label}`,
    directionEyebrow: "Dirección",
    directionHeading: "Elige qué define delante.",
    directionRelease: "Suelta todos los controles antes de cambiar la dirección.",
    frameUnavailable: "El sistema conectado no ha indicado marcos de comando.",
    frameFallback: "Usar este marco indicado por el sistema conectado.",
    frameDescriptions: {
      base_link: { label: "Ejes del robot", description: "Delante queda alineado con la base del robot." },
      effector_frame: {
        label: "Dirección de la herramienta",
        description: "Delante sigue la herramienta del extremo.",
      },
      hybrid_frame: { label: "Donde miro", description: "La traslación sigue el marco orientado al operador." },
      ft_frame: { label: "Sensor de fuerza", description: "Delante sigue el marco del sensor de fuerza." },
    },
    languageEyebrow: "Idioma",
    languageHeading: "Elige tu idioma.",
    displayEyebrow: "Leer la pantalla",
    displayHeading: "Perfil de pantalla instalado",
    displayLabel: "Pantalla",
    textSize: "Tamaño del texto",
    displayFixed: "La pantalla se configura durante la instalación de la tableta.",
    displayPresets: {
      compact: "Compacta",
      comfort: "Cómoda",
      default: "Predeterminada",
      "high-visibility": "Alta visibilidad",
    },
    safePreview: "Prueba segura",
    tryTitle: "Pruébalo aquí",
    tryHelp: "Estos botones nunca envían nada al robot.",
    tryLeft: "Izquierda",
    tryForward: "Adelante",
    tryRight: "Derecha",
  },
};
