import type { RuntimeStrings } from "./types";

export const esRuntimeStrings: RuntimeStrings = {
  language: "es",
  status: {
    connecting: "CONECTANDO",
    held: "EN MANTENIMIENTO",
    linkDown: "SIN CONEXIÓN",
    ready: "LISTO",
    stopped: "DETENIDO",
  },
  stop: {
    engage: "PARAR",
    engageAria: "Detener el robot",
    resume: "MANTENER PARA REANUDAR",
    resumeAria: "Mantener un segundo para reanudar",
  },
  control: {
    anotherOwner: "Otro operador controla este robot",
    claim: "Tomar el control",
    claiming: "Tomando el control...",
    noOwner: "Ningún operador controla este robot",
    resumeRequiresOwner: "Toma el control antes de reanudar el robot.",
    youOwn: "TIENES EL CONTROL",
  },
  scan: {
    button: "PULSADOR - pulsa Espacio o toca aquí",
    progress: (current, total) => `Barrido ${current} de ${total}.`,
  },
  tour: {
    close: "Cerrar práctica",
    complete: "Completado",
    disconnected: "Controles de práctica desconectados de los comandos del robot",
    localOnly: "Práctica local - nada aquí puede controlar el robot",
    movementFallback: "control de movimiento",
    moveBody: (controlName, directionLabel, count) =>
      `Usa ${directionLabel} en ${controlName} dos veces. Movimiento ${Math.min(count, 2)} de 2.`,
    practice: "Práctica guiada",
    progress: (complete, total) => `${complete} de ${total} pasos completados`,
    screenBody: (applicationName, screenTitle) =>
      `${applicationName} está abierta en ${screenTitle}. La barra superior muestra la sesión; el control rojo fijo la detiene.`,
    steps: {
      screen: {
        title: "Esta es tu pantalla",
        body: "La barra superior muestra la sesión y el control rojo fijo la detiene.",
        why: "La operación mantiene las salidas y la edición lejos de los controles bajo tu mano.",
        action: "Ya la he visto",
      },
      move: {
        title: "Mover el brazo",
        body: "Usa dos veces el control de movimiento indicado.",
        why: "Este control usa el nombre de la app, pero no tiene conexión con los comandos del robot.",
        action: "Avanzar",
      },
      stop: {
        title: "Parar y volver a empezar",
        body: "Detén la práctica y mantén pulsado para reanudarla.",
        why: "La parada es inmediata. Reanudar exige mantener para evitar que otro toque reinicie el movimiento.",
        action: "Parar práctica",
      },
      settings: {
        title: "Adaptarla a tu mano",
        body: "Mantén mantenimiento para encontrar los ajustes de movimiento, tiempo, dirección, idioma y pantalla.",
        why: "Los ajustes usan tu barrido y reposo actuales y la prueba nunca envía movimiento al robot.",
        action: "Mantener mantenimiento",
      },
      ready: {
        title: "Todo listo",
        body: "Sal de la práctica local y vuelve a la pantalla de operación real.",
        why: "Los controles reales solo vuelven al salir de esta práctica desconectada.",
        action: "Empezar de verdad",
      },
    },
    stepsLabel: "Pasos de práctica",
    title: "Practicar esta app",
    whyTitle: "Por qué importa",
  },
  workspace: {
    application: "Aplicación de operación",
    comingSoon: "Próximamente",
    comingSoonDescription: "Esta pantalla existe en la aplicación, pero aún no tiene contenido operativo.",
    comingSoonRegion: "Pantalla de operación próximamente",
  },
  kiosk: {
    appLibrary: "Biblioteca de apps",
    backToOperation: "Volver al control",
    commandFailed: "Comando fallido",
    commandNotSent: "No enviado",
    editApp: "Editar app",
    editScreen: "Editar esta pantalla",
    fitDescription: (width, height, percent) =>
      `Diseñada para ${width} x ${height}, mostrada al ${percent} %. Los objetivos pueden medir menos de 44 px.`,
    fitTitle: "Objetivos táctiles reducidos",
    frameNotOnRobot: (frameId) =>
      `El marco de comando "${frameId}" no está disponible en este robot. Elija un marco disponible antes de moverlo.`,
    frameReleaseControls: "Suelte los controles.",
    frameUnavailableOnRobot: "No disponible en este robot.",
    gamepad: "mando",
    help: "Ayuda",
    home: "Inicio",
    maintenance: "Mantenimiento",
    maintenanceAria: "Mantener para abrir mantenimiento",
    maintenanceHelp:
      "El movimiento se detiene mientras el mantenimiento está abierto. Devuelve los controles a posición neutra antes de reanudar.",
    referenceFrameTitle: "Marco de referencia de los comandos",
    robotTitle: "Robot controlado por este servidor",
    settings: "Ajustes",
    supervisorMirror: "Vista de supervisión",
    switchScreen: "Cambiar pantalla de operación",
    rate: (hz) => `${hz} Hz`,
    ratePublishing: (hz) => `publicando · ${hz} Hz`,
    rateZerosHeld: "ceros mantenidos",
    heldBadge: "Robot mantenido en cero",
    close: "Cerrar",
    facts: {
      appVersion: "Versión de la app",
      commandFrame: "Marco de comando",
      commandFrameNote: "en cada comando de velocidad",
      deviceClass: "Tipo de dispositivo",
      deviceDesktop: "Escritorio",
      deviceNote: (width, height) => `${width}×${height} · diseñado`,
      deviceTablet: "Tableta",
      gamepadConnected: (name) => `mando: ${name}`,
      link: "Conexión",
      linkNote: "de la interfaz al servidor, no al brazo",
      notReported: "No informado",
      profile: "Perfil",
      publishRate: "Frecuencia de envío",
      publishRateNote: "también ceros en reposo",
      youControl: "controlas el robot",
    },
    actions: "Acciones",
    settingsHint: "tamaño del texto, idioma, cómo alcanzas los controles",
    switchRole: "Cambiar de rol",
    switchRoleAria: "Mantener para cambiar de rol",
    switchRoleHint: "requiere su propia pulsación de 1,5 s",
    switchRoleChoose: "Elige un rol",
    reload: "Recargar esta app",
    reloadHint: "recarga Bloom; conserva tu perfil",
    exitToLibrary: "Salir a la biblioteca",
    exitHint: "termina la sesión",
    more: "Más",
    resumeNote:
      "Al cerrar, el envío se reanuda de inmediato. Nada aquí cambia lo que envía la app: temas, marco y frecuencia se muestran para leerlos, no para ajustarlos.",
    resume: "Reanudar la operación",
  },
  supervisor: {
    application: "Aplicación",
    backToLibrary: "Volver a la biblioteca de apps",
    activeFrame: "Marco activo",
    commandFrame: "Marco configurado",
    controlOwnerUnknown: "Propietario del control no indicado",
    driving: "En movimiento",
    holding: "Detenido",
    lastRequest: "Último modo solicitado",
    neverRequested: "No se ha observado ninguna solicitud de modo en esta sesión del navegador",
    noOperatorOwnsControl: "Ningún operador tiene el control",
    noModeRequested: "La sesión operadora no ha solicitado ningún modo",
    notReported: "No indicado",
    operatorOwnsControl: "El operador conserva el control",
    ownershipDetail:
      "Esta vista solo observa el estado. No tiene controles de movimiento, parada, reanudación, publicación ni acciones.",
    readOnly: "Estado en directo de solo lectura",
    robot: "Robot",
    running: "En marcha",
    status: {
      api: "API",
      checking: "Comprobando",
      connected: "Conectada",
      live: "Activa",
      local: "Local",
      missing: "Ausente",
      mode: "Modo",
      noPublisher: "Sin publicador",
      noSubscriber: "Sin suscriptor",
      notChecked: "No comprobado",
      panelLabel: "Estado del robot en operación",
      refresh: "Actualizar estado",
      refreshFailed: "No se pudo actualizar el estado de operación.",
      session: "Sesión",
      topicsLoaded: (count) => `${count} diagnósticos de topics cargados.`,
      topicListLabel: "Estado de los topics de operación",
      unavailable: "No disponible",
    },
    stopLatch: "Bloqueo de parada",
    stopped: "Detenido",
    title: "Vista de supervisión",
    updatedAt: (value) => `Solicitado ${value}`,
  },
  library: {
    brand: "Bloom",
    title: "Biblioteca de apps",
    appsLabel: "Apps de este robot",
    openAsLabel: "Abrir como",
    openAs: (role) => `Abrir como ${role}`,
    open: "Abrir",
    chooseRole: "Elige un rol para abrir",
    screens: (count) => (count === 1 ? "1 pantalla" : `${count} pantallas`),
    classes: {
      tablet: "Tableta",
      desktop: "Escritorio",
      both: "tableta + escritorio",
      tabletOnly: "solo tableta",
      desktopOnly: "solo escritorio",
    },
    archived: "Archivada",
    active: "activa",
    roleNote: "El último rol usado está marcado. Elegir es deliberado.",
    lastUsed: "último usado",
    noProfiles: "Esta app no declara perfiles, así que abre con los valores por defecto.",
    tagline: {
      accessible: "accesible",
      debugging: "depuración",
      scan: "barrido",
      dwell: "reposo",
      plainLanguage: "lenguaje claro",
      continuousLimits: "límites continuos",
      period: (seconds) => `periodo de ${seconds} s`,
      target: (px) => `${px} px`,
    },
    supervisorAria: (appName) => `Abrir la vista de supervisión de ${appName}`,
    thisDevice: "Este dispositivo",
    deviceTablet: (width, height) =>
      `Tableta · ${width}×${height} · táctil · mínimo 48 px, 64 px en perfiles accesibles`,
    deviceDesktop: (width, height) =>
      `Escritorio · ${width}×${height} · ratón y teclado · mínimo 40 px salvo que el perfil lo aumente`,
    empty: "Todavía no hay apps instaladas en este robot.",
    menu: "Menú de la biblioteca",
    builder: "Editor",
  },
  settings: {
    title: "Ajustes",
    practiceTour: "Recorrido de práctica",
    display: "Pantalla",
    textSize: "Tamaño del texto",
    textSizes: { normal: "Normal", large: "Grande", larger: "Más grande" },
    language: "Idioma",
    sound: "Sonido en cada pulsación",
    valueOn: "Sí",
    valueOff: "No",
    reach: "Cómo alcanzas los controles",
    inputMethod: "Método de entrada",
    inputMethods: { touch: "Tocar", dwell: "Reposo", scan: "Barrido" },
    pushMoves: "Cómo se mueve una pulsación",
    pushModes: { drag: "Arrastrar", step: "Toque a toque", latch: "Seguir" },
    onlyFor: (method) => `solo para ${method}`,
    onlyForTouchAndDwell: "solo para Tocar y Reposo",
    timing: "Tiempos",
    timingTouch: "Tiempos — tocar no necesita tiempos",
    holdToActivate: "Mantener para activar",
    scanStep: "Paso del barrido",
    ignoreRepeats: "Ignorar repeticiones en",
    deadzone: "Zona muerta del joystick",
    decrease: (label) => `Reducir ${label}`,
    increase: (label) => `Aumentar ${label}`,
    value: (label) => `Valor de ${label}`,
    tryIt: "Pruébalo — este es el control real",
    tryTitle: "Prueba una pulsación",
    tryIdle: "Pulsa para probar. No se envía nada.",
    tryPressed: (count) => `Pulsado ${count} ${count === 1 ? "vez" : "veces"}. No se envió nada.`,
    tryReadout: (targetPx, fontScale, timing) => `objetivo ${targetPx} px · texto ${fontScale} · ${timing}`,
    immediate: "inmediato",
    tryForward: "Adelante",
    saveAndResume: "Guardar y reanudar",
    savedTo: "Guardado en",
    savedToBody: (profileName) =>
      `El perfil ${profileName} en este dispositivo. No cambia lo que publica la app, solo cómo la alcanzas.`,
  },
};
