import type { RuntimeStrings } from "./types";

export const frRuntimeStrings: RuntimeStrings = {
  language: "fr",
  status: { connecting: "CONNEXION", linkDown: "LIAISON COUPÉE", ready: "PRÊT", stopped: "ARRÊTÉ" },
  stop: {
    engage: "ARRÊT",
    engageAria: "Arrêter le robot",
    resume: "MAINTENIR POUR REPRENDRE",
    resumeAria: "Maintenir une seconde pour reprendre",
  },
  scan: {
    button: "CONTACTEUR - appuyez Espace ou touchez ici",
    progress: (current, total) => `Balayage ${current} sur ${total}.`,
  },
  workspace: {
    application: "Application opérateur",
    comingSoon: "Bientôt disponible",
    comingSoonDescription: "Cet écran existe dans l'application, mais n'a pas encore de contenu opérateur.",
    comingSoonRegion: "Écran opérateur bientôt disponible",
  },
  kiosk: {
    appLibrary: "Bibliothèque d'apps",
    backToOperation: "Retour au pilotage",
    editApp: "Modifier l'app",
    editScreen: "Modifier cet écran",
    fitDescription: (width, height, percent) =>
      `Composé pour ${width} x ${height}, affiché à ${percent} %. Les cibles peuvent mesurer moins de 44 px.`,
    fitTitle: "Cibles tactiles réduites",
    gamepad: "manette",
    help: "Aide",
    home: "Accueil",
    maintenance: "Maintenance",
    maintenanceAria: "Maintenir pour ouvrir la maintenance",
    maintenanceHelp: "Maintenu 1,5 s. Le robot conserve le dernier état commandé pendant l'ouverture.",
    referenceFrameTitle: "Repère des commandes opérateur",
    robotTitle: "Robot piloté par ce serveur",
    settings: "Réglages",
    switchScreen: "Changer d'écran opérateur",
  },
  settings: {
    title: "Réglages",
    profileName: (name) => `Profil de ${name}`,
    undo: "Annuler les changements",
    done: "Terminé",
    categories: {
      movement: "Comment je le bouge",
      tuning: "Réglage fin",
      frame: "Où est l'avant",
      language: "Langue",
      display: "Lire l'écran",
    },
    movementEyebrow: "Mouvement",
    movementHeading: "Comment les commandes doivent-elles répondre ?",
    movementFallback: "Choisissez comment les commandes répondent à votre mouvement.",
    movementChoices: {
      default: { label: "Glisser", description: "Le bras bouge tant que la main reste sur la commande." },
      step: { label: "Coup par coup", description: "Chaque appui déplace d'un petit pas." },
      latch: { label: "Continuer", description: "Le mouvement continue après le relâchement ; rappuyez pour arrêter." },
      edge: { label: "Sur le bord", description: "Le déplacement par le bord n'est pas encore disponible." },
      scan: { label: "Un contacteur", description: "Un repère parcourt chaque commande disponible." },
    },
    tuningEyebrow: "Réglage fin",
    tuningHeading: "Ajustez un pas clair à la fois.",
    scanSpeed: "Vitesse de balayage",
    smallMovements: "Ignorer les petits mouvements",
    dwellLabel: "Délai avant activation",
    dwellHelp: "Rester sur une commande pour la choisir",
    restToSelect: "Repos pour choisir",
    repeatGuard: "Ignorer les appuis répétés",
    statusSounds: "Sons d'état",
    statusSoundsHelp: "Entendre l'arrêt, la perte et le retour",
    valueOn: "Oui",
    valueOff: "Non",
    decrease: (label) => `Réduire ${label}`,
    increase: (label) => `Augmenter ${label}`,
    value: (label) => `Valeur de ${label}`,
    directionEyebrow: "Direction",
    directionHeading: "Choisissez ce qui définit l'avant.",
    directionRelease: "Relâchez toutes les commandes avant de changer de direction.",
    frameUnavailable: "Le système connecté n'a annoncé aucun repère de commande.",
    frameFallback: "Utiliser ce repère annoncé par le système connecté.",
    frameDescriptions: {
      base_link: { label: "Axes du robot", description: "L'avant reste aligné sur la base du robot." },
      effector_frame: { label: "Direction de l'outil", description: "L'avant suit l'outil au bout du bras." },
      hybrid_frame: {
        label: "Là où je regarde",
        description: "La translation suit le repère orienté vers l'opérateur.",
      },
      ft_frame: { label: "Capteur d'effort", description: "L'avant suit le repère du capteur d'effort." },
    },
    languageEyebrow: "Langue",
    languageHeading: "Choisissez votre langue.",
    displayEyebrow: "Lire l'écran",
    displayHeading: "Profil d'affichage installé",
    displayLabel: "Affichage",
    textSize: "Taille du texte",
    displayFixed: "L'affichage est configuré pendant l'installation de la tablette.",
    displayPresets: {
      compact: "Compact",
      comfort: "Confort",
      default: "Par défaut",
      "high-visibility": "Haute visibilité",
    },
    safePreview: "Essai sûr",
    tryTitle: "Essayez ici",
    tryHelp: "Ces boutons n'envoient jamais rien au robot.",
    tryLeft: "Gauche",
    tryForward: "Avancer",
    tryRight: "Droite",
  },
};
