import type { RuntimeStrings } from "./types";

export const frRuntimeStrings: RuntimeStrings = {
  language: "fr",
  status: {
    connecting: "CONNEXION",
    debug: "DÉBOGAGE",
    held: "EN MAINTENANCE",
    linkDown: "LIAISON COUPÉE",
    notInControl: "SANS CONTRÔLE",
    ready: "PRÊT",
    stopped: "ARRÊTÉ",
  },
  stop: {
    engage: "ARRÊT",
    engageAria: "Arrêter le robot",
    resume: "MAINTENIR POUR REPRENDRE",
    resumeAria: "Maintenir une seconde pour reprendre",
  },
  control: {
    anotherOwner: "Un autre opérateur commande ce robot",
    claim: "Prendre le contrôle",
    claiming: "Prise de contrôle...",
    noOwner: "Aucun opérateur ne commande ce robot",
    resumeRequiresOwner: "Prenez le contrôle avant de reprendre le robot.",
    youOwn: "VOUS COMMANDEZ",
  },
  scan: {
    button: "CONTACTEUR - appuyez Espace ou touchez ici",
    progress: (current, total) => `Balayage ${current} sur ${total}.`,
  },
  tour: {
    close: "Fermer l'entraînement",
    complete: "Terminé",
    disconnected: "Commandes d'entraînement déconnectées des commandes du robot",
    localOnly: "Entraînement local - rien ici ne peut commander le robot",
    movementFallback: "commande de mouvement",
    moveBody: (controlName, directionLabel, count) =>
      `Utilisez ${directionLabel} sur ${controlName} deux fois. Mouvement ${Math.min(count, 2)} sur 2.`,
    practice: "Entraînement guidé",
    progress: (complete, total) => `${complete} étapes terminées sur ${total}`,
    screenBody: (applicationName, screenTitle) =>
      `${applicationName} est ouverte sur ${screenTitle}. Le bandeau indique la session ; la commande rouge fixe l'arrête.`,
    steps: {
      screen: {
        title: "Voici votre écran",
        body: "Le bandeau indique la session et la commande rouge fixe l'arrête.",
        why: "Le pilotage éloigne les sorties et les outils d'édition des commandes sous votre main.",
        action: "Je l'ai vu",
      },
      move: {
        title: "Déplacer le bras",
        body: "Utilisez deux fois la commande de mouvement indiquée.",
        why: "Cette commande reprend le libellé de l'app, mais n'est reliée à aucune commande du robot.",
        action: "Avancer",
      },
      stop: {
        title: "Arrêter, et repartir",
        body: "Arrêtez l'entraînement, puis maintenez pour le reprendre.",
        why: "L'arrêt est immédiat. La reprise exige un maintien pour qu'un second contact ne relance pas le mouvement.",
        action: "Arrêter l'entraînement",
      },
      settings: {
        title: "L'adapter à votre main",
        body: "Maintenez Maintenance pour trouver les réglages de mouvement, temps, direction, langue et affichage.",
        why: "Les réglages utilisent votre balayage et votre repos actuels, et l'essai n'envoie rien au robot.",
        action: "Maintenir Maintenance",
      },
      ready: {
        title: "Vous êtes prêt",
        body: "Quittez l'entraînement local et revenez à l'écran opérateur réel.",
        why: "Les vraies commandes reviennent seulement après avoir quitté cet entraînement déconnecté.",
        action: "Commencer pour de vrai",
      },
    },
    stepsLabel: "Étapes d'entraînement",
    title: "S'entraîner avec cette app",
    whyTitle: "Pourquoi c'est important",
  },
  workspace: {
    application: "Application opérateur",
    comingSoon: "Bientôt disponible",
    comingSoonDescription: "Cet écran existe dans l'application, mais n'a pas encore de contenu opérateur.",
    comingSoonRegion: "Écran opérateur bientôt disponible",
  },
  kiosk: {
    appLibrary: "Bibliothèque d'apps",
    backToOperation: "Retour au pilotage",
    commandFailed: "Commande échouée",
    commandNotSent: "Non envoyée",
    editApp: "Modifier l'app",
    editScreen: "Modifier cet écran",
    fitDescription: (width, height, percent) =>
      `Composé pour ${width} x ${height}, affiché à ${percent} %. Les cibles peuvent mesurer moins de 44 px.`,
    fitTitle: "Cibles tactiles réduites",
    frameNotOnRobot: (frameId) =>
      `Le repère de commande « ${frameId} » n'est pas disponible sur ce robot. Choisissez un repère disponible avant de bouger.`,
    frameReleaseControls: "Relâchez les commandes.",
    frameUnavailableOnRobot: "Indisponible sur ce robot.",
    gamepad: "manette",
    help: "Aide",
    home: "Accueil",
    maintenance: "Maintenance",
    maintenanceAria: "Maintenir pour ouvrir la maintenance",
    maintenanceHelp:
      "Le mouvement est arrêté pendant l'ouverture de la maintenance. Remettez les commandes au neutre avant de reprendre.",
    referenceFrameTitle: "Repère des commandes opérateur",
    robotTitle: "Robot piloté par ce serveur",
    settings: "Réglages",
    supervisorMirror: "Vue superviseur",
    switchScreen: "Changer d'écran opérateur",
    rate: (hz) => `${hz} Hz`,
    ratePublishing: (hz) => `envoi · ${hz} Hz`,
    rateZerosHeld: "zéros maintenus",
    heldBadge: "Robot maintenu à zéro",
    close: "Fermer",
    facts: {
      appVersion: "Version de l'app",
      commandFrame: "Repère de commande",
      commandFrameNote: "apposé sur chaque commande de vitesse",
      deviceClass: "Type d'appareil",
      deviceDesktop: "Ordinateur",
      deviceNote: (width, height) => `${width}×${height} · conçu pour`,
      deviceTablet: "Tablette",
      gamepadConnected: (name) => `manette : ${name}`,
      link: "Liaison",
      linkNote: "de l'interface au serveur, pas au bras",
      notReported: "Non signalé",
      profile: "Profil",
      publishRate: "Fréquence d'envoi",
      publishRateNote: "zéros au repos aussi",
      youControl: "vous pilotez le robot",
    },
    actions: "Actions",
    settingsHint: "taille du texte, langue, accès aux commandes",
    switchRole: "Changer de rôle",
    switchRoleAria: "Maintenir pour changer de rôle",
    switchRoleHint: "demande son propre appui de 1,5 s",
    switchRoleChoose: "Choisir un rôle",
    reload: "Recharger cette app",
    reloadHint: "recharge Bloom ; garde votre profil",
    exitToLibrary: "Quitter vers la bibliothèque",
    exitHint: "termine la session",
    more: "Plus",
    resumeNote:
      "Fermer reprend l'envoi immédiatement. Rien ici ne change ce que l'app envoie : sujets, repère et fréquence sont affichés pour être lus, pas réglés.",
    resume: "Reprendre le pilotage",
  },
  supervisor: {
    application: "Application",
    backToLibrary: "Retour à la bibliothèque d'apps",
    activeFrame: "Repère actif",
    commandFrame: "Repère configuré",
    controlOwnerUnknown: "Propriétaire du contrôle non indiqué",
    driving: "En mouvement",
    holding: "À l'arrêt",
    lastRequest: "Dernier mode demandé",
    neverRequested: "Aucune demande de mode observée dans cette session du navigateur",
    noOperatorOwnsControl: "Aucun opérateur ne détient le contrôle",
    noModeRequested: "Aucun mode demandé par la session opératrice",
    notReported: "Non indiqué",
    operatorOwnsControl: "L'opérateur garde le contrôle",
    ownershipDetail:
      "Cette vue observe uniquement l'état. Elle ne contient aucune commande de mouvement, d'arrêt, de reprise, de publication ou d'action.",
    readOnly: "État en direct, lecture seule",
    robot: "Robot",
    running: "En marche",
    status: {
      api: "API",
      checking: "Vérification",
      connected: "Connectée",
      live: "Active",
      local: "Locale",
      missing: "Manquant",
      mode: "Mode",
      noPublisher: "Aucun éditeur",
      noSubscriber: "Aucun abonné",
      notChecked: "Non vérifié",
      panelLabel: "État du robot en fonctionnement",
      refresh: "Actualiser l'état",
      refreshFailed: "L'actualisation de l'état a échoué.",
      session: "Session",
      topicsLoaded: (count) => `${count} diagnostics de topics chargés.`,
      topicListLabel: "État des topics d'exécution",
      unavailable: "Indisponible",
    },
    stopLatch: "Verrou d'arrêt",
    stopped: "Arrêté",
    title: "Vue superviseur",
    updatedAt: (value) => `Demandé ${value}`,
  },
  library: {
    brand: "Bloom",
    title: "Bibliothèque d'apps",
    appsLabel: "Apps de ce robot",
    openAsLabel: "Ouvrir en tant que",
    openAs: (role) => `Ouvrir en tant que ${role}`,
    open: "Ouvrir",
    chooseRole: "Choisissez un rôle pour ouvrir",
    screens: (count) => (count === 1 ? "1 écran" : `${count} écrans`),
    classes: {
      tablet: "Tablette",
      desktop: "Ordinateur",
      both: "tablette + ordinateur",
      tabletOnly: "tablette seulement",
      desktopOnly: "ordinateur seulement",
    },
    archived: "Archivée",
    active: "active",
    roleNote: "Le dernier rôle utilisé est marqué. Choisir est délibéré.",
    lastUsed: "dernier utilisé",
    noProfiles: "Cette app ne déclare aucun profil, elle s'ouvre donc avec les réglages par défaut.",
    tagline: {
      accessible: "accessible",
      debugging: "débogage",
      scan: "défilement",
      dwell: "pointage",
      plainLanguage: "langage simple",
      continuousLimits: "limites continues",
      period: (seconds) => `période de ${seconds} s`,
      target: (px) => `${px} px`,
    },
    supervisorAria: (appName) => `Ouvrir la vue superviseur de ${appName}`,
    thisDevice: "Cet appareil",
    deviceTablet: (width, height) =>
      `Tablette · ${width}×${height} · tactile · 48 px minimum, 64 px sur les profils accessibles`,
    deviceDesktop: (width, height) =>
      `Ordinateur · ${width}×${height} · souris et clavier · 40 px minimum sauf si le profil l'augmente`,
    empty: "Aucune app n'est encore installée sur ce robot.",
    menu: "Menu de la bibliothèque",
    builder: "Éditeur",
  },
  settings: {
    title: "Réglages",
    practiceTour: "Visite d'entraînement",
    display: "Affichage",
    textSize: "Taille du texte",
    textSizes: { normal: "Normale", large: "Grande", larger: "Plus grande" },
    language: "Langue",
    sound: "Son à chaque appui",
    valueOn: "Oui",
    valueOff: "Non",
    reach: "Comment vous atteignez les commandes",
    inputMethod: "Mode de saisie",
    inputMethods: { touch: "Toucher", dwell: "Pointage", scan: "Défilement" },
    pushMoves: "Comment un appui fait bouger",
    pushModes: { drag: "Glisser", step: "Pas à pas", latch: "Continuer" },
    onlyFor: (method) => `seulement pour ${method}`,
    onlyForTouchAndDwell: "seulement pour Toucher et Pointage",
    timing: "Temps",
    timingTouch: "Temps — le toucher n'en a pas besoin",
    holdToActivate: "Maintenir pour activer",
    scanStep: "Pas du défilement",
    ignoreRepeats: "Ignorer les répétitions sous",
    deadzone: "Zone morte du joystick",
    deadzoneWidgetDefault: "celle de chaque commande",
    decrease: (label) => `Diminuer ${label}`,
    increase: (label) => `Augmenter ${label}`,
    value: (label) => `Valeur de ${label}`,
    tryIt: "Essayez — rien n'est envoyé",
    tryTitle: "Essayez un appui",
    tryIdle: "Appuyez pour essayer. Rien n'est envoyé.",
    tryPressed: (count) => `Appuyé ${count} fois. Rien n'a été envoyé.`,
    tryReadout: (targetPx, fontScale, timing) => `cible ${targetPx} px · texte ${fontScale} · ${timing}`,
    immediate: "immédiat",
    tryForward: "Avant",
    saveAndResume: "Enregistrer et reprendre",
    discardChanges: "Annuler les modifications",
    savedTo: "Enregistré dans",
    savedToBody: (profileName) =>
      `Le profil ${profileName} sur cet appareil. Il ne change pas ce que l'app publie, seulement comment vous l'atteignez.`,
  },
};
