import type { RuntimeStrings } from "./types";

export const frRuntimeStrings: RuntimeStrings = {
  language: "fr",
  status: { connecting: "CONNEXION", linkDown: "LIAISON COUPÉE", ready: "PRÊT", stopped: "ARRÊTÉ" },
  stop: {
    engage: "ARRÊT",
    engageAria: "Arrêter le robot",
    resume: "MAINTENIR POUR REPRENDRE",
    resumeAria: "Maintenir une seconde pour reprendre",
  },
  scan: {
    button: "CONTACTEUR - appuyez Espace ou touchez ici",
    progress: (current, total) => `Balayage ${current} sur ${total}.`,
  },
  tour: {
    close: "Fermer l'entraînement",
    complete: "Terminé",
    disconnected: "Commandes d'entraînement déconnectées des commandes du robot",
    localOnly: "Entraînement local - rien ici ne peut commander le robot",
    movementFallback: "commande de mouvement",
    moveBody: (controlName, directionLabel, count) =>
      `Utilisez ${directionLabel} sur ${controlName} deux fois. Mouvement ${Math.min(count, 2)} sur 2.`,
    practice: "Entraînement guidé",
    progress: (complete, total) => `${complete} étapes terminées sur ${total}`,
    screenBody: (applicationName, screenTitle) =>
      `${applicationName} est ouverte sur ${screenTitle}. Le bandeau indique la session ; la commande rouge fixe l'arrête.`,
    steps: {
      screen: {
        title: "Voici votre écran",
        body: "Le bandeau indique la session et la commande rouge fixe l'arrête.",
        why: "Le pilotage éloigne les sorties et les outils d'édition des commandes sous votre main.",
        action: "Je l'ai vu",
      },
      move: {
        title: "Déplacer le bras",
        body: "Utilisez deux fois la commande de mouvement indiquée.",
        why: "Cette commande reprend le libellé de l'app, mais n'est reliée à aucune commande du robot.",
        action: "Avancer",
      },
      stop: {
        title: "Arrêter, et repartir",
        body: "Arrêtez l'entraînement, puis maintenez pour le reprendre.",
        why: "L'arrêt est immédiat. La reprise exige un maintien pour qu'un second contact ne relance pas le mouvement.",
        action: "Arrêter l'entraînement",
      },
      settings: {
        title: "L'adapter à votre main",
        body: "Maintenez Maintenance pour trouver les réglages de mouvement, temps, direction, langue et affichage.",
        why: "Les réglages utilisent votre balayage et votre repos actuels, et l'essai n'envoie rien au robot.",
        action: "Maintenir Maintenance",
      },
      ready: {
        title: "Vous êtes prêt",
        body: "Quittez l'entraînement local et revenez à l'écran opérateur réel.",
        why: "Les vraies commandes reviennent seulement après avoir quitté cet entraînement déconnecté.",
        action: "Commencer pour de vrai",
      },
    },
    stepsLabel: "Étapes d'entraînement",
    title: "S'entraîner avec cette app",
    whyTitle: "Pourquoi c'est important",
  },
  workspace: {
    application: "Application opérateur",
    comingSoon: "Bientôt disponible",
    comingSoonDescription: "Cet écran existe dans l'application, mais n'a pas encore de contenu opérateur.",
    comingSoonRegion: "Écran opérateur bientôt disponible",
  },
  kiosk: {
    appLibrary: "Bibliothèque d'apps",
    backToOperation: "Retour au pilotage",
    commandFailed: "Commande échouée",
    commandNotSent: "Non envoyée",
    editApp: "Modifier l'app",
    editScreen: "Modifier cet écran",
    fitDescription: (width, height, percent) =>
      `Composé pour ${width} x ${height}, affiché à ${percent} %. Les cibles peuvent mesurer moins de 44 px.`,
    fitTitle: "Cibles tactiles réduites",
    gamepad: "manette",
    help: "Aide",
    home: "Accueil",
    maintenance: "Maintenance",
    maintenanceAria: "Maintenir pour ouvrir la maintenance",
    maintenanceHelp:
      "Le mouvement est arrêté pendant l'ouverture de la maintenance. Remettez les commandes au neutre avant de reprendre.",
    referenceFrameTitle: "Repère des commandes opérateur",
    robotTitle: "Robot piloté par ce serveur",
    settings: "Réglages",
    supervisorMirror: "Vue superviseur",
    switchScreen: "Changer d'écran opérateur",
  },
  supervisor: {
    application: "Application",
    backToLibrary: "Retour à la bibliothèque d'apps",
    commandFrame: "Repère configuré",
    lastRequest: "Dernier mode demandé",
    neverRequested: "Aucune demande de mode observée dans cette session du navigateur",
    notReported: "Non indiqué",
    operatorOwnsControl: "L'opérateur garde le contrôle",
    ownershipDetail:
      "Cette vue observe uniquement l'état. Elle ne contient aucune commande de mouvement, d'arrêt, de reprise, de publication ou d'action.",
    readOnly: "État en direct, lecture seule",
    robot: "Robot",
    running: "En marche",
    status: {
      api: "API",
      checking: "Vérification",
      connected: "Connectée",
      live: "Active",
      local: "Locale",
      missing: "Manquant",
      mode: "Mode",
      noPublisher: "Aucun éditeur",
      noSubscriber: "Aucun abonné",
      notChecked: "Non vérifié",
      panelLabel: "État du robot en fonctionnement",
      refresh: "Actualiser l'état",
      refreshFailed: "L'actualisation de l'état a échoué.",
      session: "Session",
      topicsLoaded: (count) => `${count} diagnostics de topics chargés.`,
      topicListLabel: "État des topics d'exécution",
      unavailable: "Indisponible",
    },
    stopLatch: "Verrou d'arrêt",
    stopped: "Arrêté",
    title: "Vue superviseur",
    updatedAt: (value) => `Demandé ${value}`,
  },
  settings: {
    title: "Réglages",
    profileName: (name) => `Profil de ${name}`,
    practiceTour: "Entraînement guidé",
    undo: "Annuler les changements",
    done: "Terminé",
    categories: {
      movement: "Comment je le bouge",
      tuning: "Réglage fin",
      frame: "Où est l'avant",
      language: "Langue",
      display: "Lire l'écran",
    },
    movementEyebrow: "Mouvement",
    movementHeading: "Comment les commandes doivent-elles répondre ?",
    movementFallback: "Choisissez comment les commandes répondent à votre mouvement.",
    movementChoices: {
      default: { label: "Glisser", description: "Le bras bouge tant que la main reste sur la commande." },
      step: { label: "Coup par coup", description: "Chaque appui déplace d'un petit pas." },
      latch: { label: "Continuer", description: "Le mouvement continue après le relâchement ; rappuyez pour arrêter." },
      edge: { label: "Sur le bord", description: "Le déplacement par le bord n'est pas encore disponible." },
      scan: { label: "Un contacteur", description: "Un repère parcourt chaque commande disponible." },
    },
    tuningEyebrow: "Réglage fin",
    tuningHeading: "Ajustez un pas clair à la fois.",
    scanSpeed: "Vitesse de balayage",
    smallMovements: "Ignorer les petits mouvements",
    dwellLabel: "Délai avant activation",
    dwellHelp: "Rester sur une commande pour la choisir",
    restToSelect: "Repos pour choisir",
    repeatGuard: "Ignorer les appuis répétés",
    statusSounds: "Sons d'état",
    statusSoundsHelp: "Entendre l'arrêt, la perte et le retour",
    valueOn: "Oui",
    valueOff: "Non",
    decrease: (label) => `Réduire ${label}`,
    increase: (label) => `Augmenter ${label}`,
    value: (label) => `Valeur de ${label}`,
    directionEyebrow: "Direction",
    directionHeading: "Choisissez ce qui définit l'avant.",
    directionRelease: "Relâchez toutes les commandes avant de changer de direction.",
    frameUnavailable: "Le système connecté n'a annoncé aucun repère de commande.",
    frameFallback: "Utiliser ce repère annoncé par le système connecté.",
    frameDescriptions: {
      base_link: { label: "Axes du robot", description: "L'avant reste aligné sur la base du robot." },
      effector_frame: { label: "Direction de l'outil", description: "L'avant suit l'outil au bout du bras." },
      hybrid_frame: {
        label: "Là où je regarde",
        description: "La translation suit le repère orienté vers l'opérateur.",
      },
      ft_frame: { label: "Capteur d'effort", description: "L'avant suit le repère du capteur d'effort." },
    },
    languageEyebrow: "Langue",
    languageHeading: "Choisissez votre langue.",
    displayEyebrow: "Lire l'écran",
    displayHeading: "Profil d'affichage installé",
    displayLabel: "Affichage",
    textSize: "Taille du texte",
    displayFixed: "L'affichage est configuré pendant l'installation de la tablette.",
    displayPresets: {
      compact: "Compact",
      comfort: "Confort",
      default: "Par défaut",
      "high-visibility": "Haute visibilité",
    },
    safePreview: "Essai sûr",
    tryTitle: "Essayez ici",
    tryHelp: "Ces boutons n'envoient jamais rien au robot.",
    tryLeft: "Gauche",
    tryForward: "Avancer",
    tryRight: "Droite",
  },
};
