import type { DisplayPreset, RuntimeLanguage } from "@bloom/api-client";

export type RuntimeStrings = {
  language: RuntimeLanguage;
  status: { connecting: string; linkDown: string; ready: string; stopped: string };
  stop: { engage: string; engageAria: string; resume: string; resumeAria: string };
  scan: { button: string; progress: (current: number, total: number) => string };
  tour: {
    close: string;
    complete: string;
    disconnected: string;
    localOnly: string;
    movementFallback: string;
    moveBody: (controlName: string, directionLabel: string, count: number) => string;
    practice: string;
    progress: (complete: number, total: number) => string;
    screenBody: (applicationName: string, screenTitle: string) => string;
    steps: Record<
      "move" | "ready" | "screen" | "settings" | "stop",
      { action: string; body: string; title: string; why: string }
    >;
    stepsLabel: string;
    title: string;
    whyTitle: string;
  };
  workspace: {
    application: string;
    comingSoon: string;
    comingSoonDescription: string;
    comingSoonRegion: string;
  };
  kiosk: {
    appLibrary: string;
    backToOperation: string;
    editApp: string;
    editScreen: string;
    fitDescription: (width: number, height: number, percent: number) => string;
    fitTitle: string;
    gamepad: string;
    help: string;
    home: string;
    maintenance: string;
    maintenanceAria: string;
    maintenanceHelp: string;
    referenceFrameTitle: string;
    robotTitle: string;
    settings: string;
    supervisorMirror: string;
    switchScreen: string;
  };
  supervisor: {
    application: string;
    backToLibrary: string;
    commandFrame: string;
    lastRequest: string;
    neverRequested: string;
    notReported: string;
    operatorOwnsControl: string;
    ownershipDetail: string;
    readOnly: string;
    robot: string;
    running: string;
    status: {
      api: string;
      checking: string;
      connected: string;
      live: string;
      local: string;
      missing: string;
      mode: string;
      noPublisher: string;
      noSubscriber: string;
      notChecked: string;
      panelLabel: string;
      refresh: string;
      refreshFailed: string;
      session: string;
      topicsLoaded: (count: number) => string;
      topicListLabel: string;
      unavailable: string;
    };
    stopLatch: string;
    stopped: string;
    title: string;
    updatedAt: (value: string) => string;
  };
  settings: {
    categories: { display: string; frame: string; language: string; movement: string; tuning: string };
    decrease: (label: string) => string;
    directionEyebrow: string;
    directionHeading: string;
    directionRelease: string;
    displayEyebrow: string;
    displayFixed: string;
    displayHeading: string;
    displayLabel: string;
    displayPresets: Record<DisplayPreset, string>;
    done: string;
    dwellHelp: string;
    dwellLabel: string;
    frameDescriptions: Record<string, { description: string; label: string }>;
    frameFallback: string;
    frameUnavailable: string;
    increase: (label: string) => string;
    languageEyebrow: string;
    languageHeading: string;
    movementChoices: Record<"default" | "edge" | "latch" | "scan" | "step", { description: string; label: string }>;
    movementEyebrow: string;
    movementFallback: string;
    movementHeading: string;
    profileName: (name: string) => string;
    practiceTour: string;
    repeatGuard: string;
    restToSelect: string;
    safePreview: string;
    scanSpeed: string;
    smallMovements: string;
    statusSounds: string;
    statusSoundsHelp: string;
    textSize: string;
    title: string;
    tryForward: string;
    tryHelp: string;
    tryLeft: string;
    tryRight: string;
    tryTitle: string;
    tuningEyebrow: string;
    tuningHeading: string;
    undo: string;
    value: (label: string) => string;
    valueOff: string;
    valueOn: string;
  };
};
