import type { DisplayPreset, RuntimeLanguage } from "@bloom/api-client";

export type RuntimeStrings = {
  language: RuntimeLanguage;
  status: { connecting: string; linkDown: string; ready: string; stopped: string };
  stop: { engage: string; engageAria: string; resume: string; resumeAria: string };
  scan: { button: string; progress: (current: number, total: number) => string };
  workspace: {
    application: string;
    comingSoon: string;
    comingSoonDescription: string;
    comingSoonRegion: string;
  };
  kiosk: {
    appLibrary: string;
    backToOperation: string;
    editApp: string;
    editScreen: string;
    fitDescription: (width: number, height: number, percent: number) => string;
    fitTitle: string;
    gamepad: string;
    help: string;
    home: string;
    maintenance: string;
    maintenanceAria: string;
    maintenanceHelp: string;
    referenceFrameTitle: string;
    robotTitle: string;
    settings: string;
    switchScreen: string;
  };
  settings: {
    categories: { display: string; frame: string; language: string; movement: string; tuning: string };
    decrease: (label: string) => string;
    directionEyebrow: string;
    directionHeading: string;
    directionRelease: string;
    displayEyebrow: string;
    displayFixed: string;
    displayHeading: string;
    displayLabel: string;
    displayPresets: Record<DisplayPreset, string>;
    done: string;
    dwellHelp: string;
    dwellLabel: string;
    frameDescriptions: Record<string, { description: string; label: string }>;
    frameFallback: string;
    frameUnavailable: string;
    increase: (label: string) => string;
    languageEyebrow: string;
    languageHeading: string;
    movementChoices: Record<"default" | "edge" | "latch" | "scan" | "step", { description: string; label: string }>;
    movementEyebrow: string;
    movementFallback: string;
    movementHeading: string;
    profileName: (name: string) => string;
    repeatGuard: string;
    restToSelect: string;
    safePreview: string;
    scanSpeed: string;
    smallMovements: string;
    statusSounds: string;
    statusSoundsHelp: string;
    textSize: string;
    title: string;
    tryForward: string;
    tryHelp: string;
    tryLeft: string;
    tryRight: string;
    tryTitle: string;
    tuningEyebrow: string;
    tuningHeading: string;
    undo: string;
    value: (label: string) => string;
    valueOff: string;
    valueOn: string;
  };
};
