import type { RuntimeLanguage } from "@bloom/api-client";

export type RuntimeStrings = {
  language: RuntimeLanguage;
  status: {
    connecting: string;
    debug: string;
    held: string;
    linkDown: string;
    notInControl: string;
    ready: string;
    stopped: string;
  };
  stop: {
    engage: string;
    engageAria: string;
    resume: string;
    resumeAria: string;
    resumeConfirm: string;
    resumeConfirmAria: string;
  };
  control: {
    anotherOwner: string;
    claim: string;
    claiming: string;
    noOwner: string;
    resumeRequiresOwner: string;
  };
  scan: { button: string; progress: (current: number, total: number) => string };
  tour: {
    close: string;
    complete: string;
    disconnected: string;
    localOnly: string;
    movementFallback: string;
    moveBody: (controlName: string, directionLabel: string, count: number) => string;
    offerAria: string;
    offerDismiss: string;
    offerStart: string;
    practice: string;
    progress: (complete: number, total: number) => string;
    screenBody: (applicationName: string, screenTitle: string) => string;
    steps: Record<
      "move" | "ready" | "screen" | "settings" | "stop",
      { action: string; body: string; title: string; why: string }
    >;
    stepsLabel: string;
    title: string;
    whyTitle: string;
  };
  workspace: {
    application: string;
    comingSoon: string;
    comingSoonDescription: string;
    comingSoonRegion: string;
  };
  kiosk: {
    appLibrary: string;
    backToOperation: string;
    commandFailed: string;
    commandNotSent: string;
    editApp: string;
    editScreen: string;
    fitDescription: (width: number, height: number, percent: number) => string;
    fitTitle: string;
    frameNotOnRobot: (frameId: string) => string;
    frameReleaseControls: string;
    teleopTargetNotInApp: (topic: string) => string;
    teleopTargetRefusedByServer: (topic: string) => string;
    frameUnavailableOnRobot: string;
    gamepad: string;
    help: string;
    home: string;
    maintenance: string;
    maintenanceAria: string;
    maintenanceHelp: string;
    referenceFrameTitle: string;
    settings: string;
    supervisorMirror: string;
    switchScreen: string;
    rate: (hz: number) => string;
    ratePublishing: (hz: number) => string;
    rateZerosHeld: string;
    heldBadge: string;
    stoppedBadge: string;
    close: string;
    facts: {
      app: string;
      commandFrame: string;
      commandFrameNote: string;
      deviceClass: string;
      deviceDesktop: string;
      deviceNote: (width: number, height: number) => string;
      deviceTablet: string;
      gamepadConnected: (name: string) => string;
      link: string;
      linkNote: string;
      notReported: string;
      profile: string;
      publishRate: string;
      publishRateNote: string;
      youControl: string;
    };
    actions: string;
    settingsHint: string;
    switchRole: string;
    switchRoleAria: string;
    switchRoleHint: string;
    switchRoleChoose: string;
    reload: string;
    reloadHint: string;
    exitToLibrary: string;
    exitHint: string;
    more: string;
    resumeNote: string;
    resume: string;
  };
  supervisor: {
    application: string;
    backToLibrary: string;
    activeFrame: string;
    commandFrame: string;
    driving: string;
    holding: string;
    noModeRequested: string;
    controlOwnerUnknown: string;
    lastRequest: string;
    neverRequested: string;
    notReported: string;
    noOperatorOwnsControl: string;
    operatorOwnsControl: string;
    ownershipDetail: string;
    readOnly: string;
    robot: string;
    running: string;
    status: {
      api: string;
      checking: string;
      connected: string;
      live: string;
      local: string;
      missing: string;
      mode: string;
      noPublisher: string;
      noSubscriber: string;
      notChecked: string;
      panelLabel: string;
      refresh: string;
      refreshFailed: string;
      session: string;
      topicsLoaded: (count: number) => string;
      topicListLabel: string;
      unavailable: string;
    };
    stopLatch: string;
    stopped: string;
    title: string;
    updatedAt: (value: string) => string;
  };
  library: {
    active: string;
    appsLabel: string;
    archived: string;
    brand: string;
    builder: string;
    classes: Record<"both" | "desktop" | "desktopOnly" | "tablet" | "tabletOnly", string>;
    deviceDesktop: (width: number, height: number) => string;
    deviceTablet: (width: number, height: number) => string;
    empty: string;
    lastUsed: string;
    menu: string;
    noProfiles: string;
    open: string;
    openAs: (role: string) => string;
    openAsLabel: string;
    roleNote: string;
    screens: (count: number) => string;
    supervisorAria: (appName: string) => string;
    tagline: {
      accessible: string;
      continuousLimits: string;
      debugging: string;
      dwell: string;
      period: (seconds: string) => string;
      plainLanguage: string;
      scan: string;
      target: (px: number) => string;
    };
    thisDevice: string;
    title: string;
  };
  settings: {
    decrease: (label: string) => string;
    deadzone: string;
    deadzoneWidgetDefault: string;
    discardChanges: string;
    display: string;
    holdToActivate: string;
    ignoreRepeats: string;
    immediate: string;
    increase: (label: string) => string;
    inputMethod: string;
    inputMethods: Record<"dwell" | "scan" | "touch", string>;
    language: string;
    onlyFor: (method: string) => string;
    onlyForTouchAndDwell: string;
    practiceTour: string;
    pushModes: Record<"drag" | "latch" | "step", string>;
    pushMoves: string;
    reach: string;
    saveAndResume: string;
    savedTo: string;
    savedToBody: (profileName: string) => string;
    scanStep: string;
    sound: string;
    textSize: string;
    textSizes: Record<"large" | "larger" | "normal", string>;
    timing: string;
    timingTouch: string;
    title: string;
    tryForward: string;
    tryIdle: string;
    tryIt: string;
    tryPressed: (count: number) => string;
    tryReadout: (targetPx: number, fontScale: string, timing: string) => string;
    tryTitle: string;
    value: (label: string) => string;
    valueOff: string;
    valueOn: string;
  };
};
